# if this file ends in .yml, you should not edit it and edit circle.org instead.
version: 2

jobs:
  upload:
    working_directory: /build
    docker:
      - image: alpine:latest
        environment:
          S3_BUCKET: moz-devservices-bmocartons
    steps:
      - run:
          command: |
            apk update
            apk add curl # installs ca certs
      - attach_workspace:
          at: /build/upload
      - run:
          name: install awscli
          command: |
            apk update
            apk add py-pip
            pip install awscli
      - run:
          working_directory: /build/upload
          command: |
            for file in */vendor.tar.gz; do
              aws s3 cp $file s3://$S3_BUCKET/$file;
            done
  centos6:
    working_directory: /build
    docker:
      - image: centos:6.9
        environment: 
          PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
          NAME: bmo # named this for historical reasons
    steps:
      - checkout
      - run:
          name: install rpms
          command: /build/bundle/centos6/install-rpms
      - run:
          name: copy cpanfile and cpanfile.snapshot
          command: cp bundle/$CIRCLE_JOB/cpanfile* .
      - run: build-prepare
      - run: build-stage1
      - run: build-stage2
      - run: build-vendor-bundle $NAME
      - persist_to_workspace:
          root: /build/upload
          paths:
            - "*/vendor.tar.gz"
      - store_artifacts:
          path: '/root/.cpanm/work/*/build.log'
  bmo-slim:
    working_directory: /build
    docker:
      - image: docker:17.06.1-ce
        environment:
          DOCKERHUB_REPO: mozillabteam/bmo-slim
          PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: /build/upload
      - run:
          working_directory: /build/docker/bmo-slim
          command: |
            tar -zxf /build/upload/bmo/vendor.tar.gz \
              bmo/vendor/bin \
              bmo/local \
              bmo/cpanfile \
              bmo/cpanfile.snapshot \
              bmo/LIBS.txt \
              bmo/PACKAGES.txt
            docker-build
  
  docker-centos6:
    working_directory: /build
    docker:
      - image: docker:17.06.1-ce
        environment:
          DOCKERHUB_REPO: mozillabteam/centos6
          PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build docker container
          command: |
            docker-build -f bundle/centos6/Dockerfile

workflows:
  version: 2
  builders:
    jobs:
      - docker-centos6:
          filters:
            branches:
              only: master
  bundles:
    jobs:
      - centos6:
          filters:
            branches:
              only: master
      - bmo-slim:
          filters:
            branches:
              only: master
          requires:
            - centos6
      - upload:
          filters:
            branches:
              only: master
          requires:
            - centos6
